= Environmental Information Australia Supermodel
:favicon: images/logo-qld.svg
:toc: left
:toclevels: 3
:table-stripes: even
:sectnums:
:sectids:
:sectanchors:

image::images/dcceew-logo-blue.svg[width=500,float="center",align="center"]

image::images/eia-supermodel-parts.svg[width=750,float="center",align="center"]

This 'Supermodel' is a set of data models used by DCCEEW to integrate data from formerly separate systems into an interoperable whole.

As of July 2025, this Supermodel is used for data integrations only.

[NOTE]
====
This Supermodel is demonstrated through the https://eia.testing.bdr.gov.au[EIA Test Catalogue], online via the Biodiversity Data Repository's infrastructure.
====

== Metadata

[width=85%, frame=none, grid=none, cols="2,5"]
|===
|**IRI** | https://linked.data.gov.au/def/eia-supermodel
|**Title** | EIA Supermodel
|**Description** | This is an overarching model - a Supermodel - used to integrate multiple, individual, models together for use within a particular scenario.
|**Created** | 2025-02-15
|**Modified** | 2025-08-04
|**Issued** | 0000-00-00 - not in production use yet
|**Version** | 1
|**Creator** | https://kurrawong.ai[KurrawongAI], for DCCEEW
|**Publisher** | https://linked.data.gov.au/org/dcceew[Department of Climate Change, Energy, the Environment and Water (DCCEEW)]
|**License** | https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International (CC BY 4.0)]
|**Code Repository** | https://github.com/dcceew-bdr/eia-supermodel
|===

== Introduction

=== What is a Supermodel

A "supermodel" is a set of models that have been designed to allow for the integration of data from different datasets. They achieve this by ensuring the models for each dataset implement the same patterns for common elements, such as spatiality, and they contain reference data, such as controlled vocabularies of values, that the datasets refer to, providing join points.

This Supermodel follows the generic Supermodel Model defined at https://linked.data.gov.au/def/supermodel.

=== This Supermodel's Origins

Like all large and long-term data holders, the https://linked.data.gov.au/org/dcceew[Department of Climate Change, Energy, the Environment and Water (DCCEEW)] has many datasets that while they are conceptually related - within the environment domain - have been created separately and without interoperability as a priority. As a result, analysts must put lots of effort into aligning data before using multiple datasets together; effort that is likely duplicated by analysts unaware of others' work.

In early 2025, DCCEEW conducted a demonstration project called the _EIA Supermodel Demonstrator_ that aimed at showing how integration-ready data might appear and be used.

The target datasets for this work were several within DCCEEW's _Environmental Information Australia_ initiative and DCCEEW's then new https://bdr.gov.au[Biodiversity Data Repository] was used as the reference dataset: the one who's form subsets of other datasets would emulate. This was due to the BDR having been designed specifically for integration.

=== Dataset Scope

The scope of this Supermodel was set within its establishment project to initially cover data from 7 DCCEEW datasets:

1. https://www.dcceew.gov.au/environment/environment-information-australia/national-vegetation-information-system[National Vegetation Information system (NVIS)]
2. https://www.dcceew.gov.au/environment/biodiversity/threatened[Species Risks Assessment Tool (SPRAT)]
3. https://fed.dcceew.gov.au/maps/13cce3e3f8f947d487ef788cdf5a0165/about[Habitat Condition Assessment System (HCAS)]
4. https://doi.org/10.1038/s41597-021-01006-6[Australian National Flora Traits (AusTraits)]
5. https://ansis.net[Australian National Soil Information System (ANSIS)]
6. https://bdr.gov.au[Biodiversity Data Repository (BDR)]
7. https://biodiversity.org.au[National Species List (NSL)]

This Supermodel contains _Component Models_ and partial, demonstration, datasets for each of these datasets, as well as 20+ supporting assets - background datasets, vocabularies, data validators - formulated according to the Supermodel Model specification. These are detailed below.

Together, the _Component Models_, _Background Models_ and other Supermodel elements allow all the parts of the DCCEEW datasets to be integrated with all other parts, for example, the spatial parts of any two datasets may be overlayed, the observations from datasets that contain them can be used together with common data structure and reference values.

=== Modelling System

All the models in this Supermodel are implemented using the <<OWL, _Web Ontology Language_ OWL>>. OWL is a very widely used, standardised, formal modelling language. Unlike <<UML, UML>> models, OWL models natively have machine-readable forms allowing data made according to them to be automatically validated and processed into databases.

The BDR is natively modelled in OWL using the https://linked.data.gov.au/def/abis[ABIS] and AusTraits is too, using the https://bioportal.bioontology.org/ontologies/OBOE[OBOE], https://github.com/EcologicalTraitData/ETS[ETS] and https://dwc.tdwg.org/terms/[Darwin Core] models. There is a https://raw.githack.com/ANZSoilData/def-au-domain/main/doc/domain.html[pre-existing ANSIS OWL ontology] too, into which it's easy to transform data delivering service responses. The other 3 datasets - NVIS, SPRAT and HCAS - have had models, or partial model in OWL created for them, for the first time, within the project that generated this Supermodel

The Supermodel's constituent models are related to one another using <<PROF, _The Profiles Vocabulary_ PROF>> which provides properties to indicate when and how one model reuses - "<<profile, profiles>>" - another. PROF also links models to validators created to test data claiming conformance to them.

The technical presentation of data modelled in OWL is in <<RDF>> which is a graph ('node-edge-node') data structure. RDF allows models and data according to the models to be stored in files or databases of the same sort. RDF is also infinitely extensible, allowing for not just model change and growth but for easy schema change and growth too.

=== Use of Patterns

Integrated use of multiple Component Models depends on each of them implementing, or mapping to, model elements in the Background Models referred to as <<pattern, patterns>>. The patterns of relevance to this EIA Supermodel do not make a finite list as patterns can exist within and overlap other patterns, however the <<Patterns, Patterns>> section lists a set of patterns that covers the scoped datasets' implementation at least once over completely.

=== Validation

For demonstrable interoperability, this Supermodel contains data validators for some of its Background and Component Models that test data claiming conformance to it against identified patterns. These validators are executable model specifications.

Some of the validators for the models within this Supermodel were created by the original model implementors, e.g. ABIS, but others have had validators created for this through the EIA Demonstrator project.

The <<Validators, Validators>> section below lists all the validators relevant to this Supermodel and indicates their dependencies. It also includes a union validator that combines all the others and can be used to validate any data wishing to conform to this Supermodel.

=== Definitions

Here is a list of terms and acronyms used in this document.

[[BM]] Background Model:: A role within a Supermodel for low level or generic models that some, but not necessarily all, of the <<Component Models>> reuse and extend, depending on the patterns of data they contain.

[[CM]] Component Model:: A role within a Supermodel for the models of individual datasets within the set aiming for interoperability. Component Models must reuse and extend the Background Models.

Feature:: The class of object for "Anything spatial (being or having a shape, position or an extent)", according to <<GEO, GeoSPARQL>>

[[IRI]] IRI:: Internationalized Resource Identifiers (IRIs) are Internet protocol standard identifiers used to identify, and often to link to representations of, resources. IRIs add internationalisation (use of different character sets to) Uniform Resource Identifiers (URIs) which are a superset of Uniform Resource Locators (URLs). Where URLs - web addresses - must link to resources, URIs often do but need not. https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier[[ref]]

[[pattern]] pattern:: In the context of a Supermodel, a pattern is a small data model and Background Models implement many patterns within them, either implicitly or explicitly

[[profile]] profile:: "A specification that constrains, extends, combines, or provides guidance or explanation about the usage of other specifications" according to <<PROF, The Profiles Vocabulary>>.

[[SM]] Supermodel:: A set of integrated data models used with defined roles used to make multiple datasets interoperable.

[[UML]] Unified Modelling Language, UML:: A general-purpose visual modeling language that is intended to provide a standard way to visualize the design of a system. https://en.wikipedia.org/wiki/Unified_Modeling_Language[[ref]]

Vocabulary:: A controlled set of defined terms. Within Supermodel contexts, all vocabularies reuse and extend the <<SKOS, SKOS>> vocabulary model.

Web Ontology Language, OWL:: A widely used international standard modelling language that allows for machine-readability of models.

=== Machine-readable form

Like all the models within this Supermodel, the Supermodel itself has a machine-readable form that lists and relates all its elements:

* **https://linked.data.gov.au/def/eia-supermodel.ttl**

== Patterns



== Models

=== Component Models

Of the 7 Datasets in this Supermodel's <<Dataset Scope, scope>>:

AusTraits:: follows an international domain ontology, <<ETS, Ecological Trait-data Standard>> compatible with this Supermodel
BDR:: implements an profile of the Australian Semantic Web data exchange standard, <<ABIS, ABIS>> which this Supermodel incorporates
ANSIS & NSL:: have purpose-built ontologies, <<ANSISO, ANSIS Ontology>> & <<NSLMODEL, NSL Model>> compatible with ABIS and this Supermodel
NVIS & HCAS:: don't need Component Models as their concerns can be represented using this Supermodel's Background Models
Reference Areas:: conforms to <<GEO, GeoSPARQL>>, the background spatial model

Only one dataset, SPRAT, is not yet bound in to the Supermodel by one of the methods applied to the other 6. This is planned to happen soon.

The AusTraits to NSL Mapping Linkset doesn't need a Component Model either _IF_ a single predicate can be added to either AusTraits.

=== Background Models


== Vocabularies

Some of the vocabularies within this Supermodel are relevant to all datasets within this Supermodel's data <<Dataset Scope, scope>>, others just to particular Component Models.

Those relevant to all datasets are required for use by the <<EIADP, EIA Data Profile>> and are:

* http://vocabs.lter-europe.net/EnvThes[EnvThes]
** "a set of terms in order to describe in a harmonised way data resulting from observations and measurements of ecosystem processes across different domain specific sciences"
* https://linked.data.gov.au/eia-dk[EIA Data Kinds Vocabulary]

Each dataset claiming conformance to this Supermodel must be classified according to at least one EnvThes term

The vocabularies relevant to individual Component Models and Background Models are defined by those models, however, here is a table of many of them and the models to which they are relevant:

|===
| Model / Dataset | Vocabulary

| ANSIS  / <<ANSISO, ANSIS Ontology |
Land Surface classifiers
Soil Profile classifiers
Substrate classifiers
Australian Land Use and Management Classification
| - / NVIS | NVIS Major Vegetation Groups and Major Vegetation Subgroups


AusTraits Plant Dictionary glossary


|===



== Validators

The validators relevant to this Supermodel come from a range of sources and some derive from and extend on others. The following table lists all of them with derivation notes.

|===
| Validator | Derived From | Relevant Models | Notes

| ABIS Validators | <<ABIS, ABIS>> | ABIS | Validates all aspects of ABIS data from
| <<LOCIDP, Loc-I Data Profile>> | <<DCAT, DCAT>> | DCAT, <<SDO, schema.org>> | Requires minimum metadata for catalogued datasets containing spatial data
| <<EIADP, EIA Data Profile>> | Loc-I Data Profile | DCAT, schema.org | Requires minimum environmental domain dataset metadata
| GeoSPARQL 1.1 validator | <<GEO, GeoSPARQL>> | GeoSPARQL | Basic GeosPARQL validation
| <<VOCPUB, VocPub>> | DCAT, <<SKOS, SKOS>> | DCAT, SKOS | Requires minimum cataloguing metadata and structural composition for SKOS vocabularies
|===

All the validators used within this Supermodel are implemented in <<SHACL, SHACL>>, an <<RDF>> data validation language and validation of data may be carried out as per the https://linked.data.gov.au/def/abis#_performing_validation[ABIS' _Performing Validation_] section.

== References

[[ABIS]] ABIS: Australian Biodiversity Information Governance Group, _Australian Biodiversity Information Standard_. Australian government data standard (4 December 2023). https://linked.data.gov.au/def/abis

[[ANSISO]] ANSISO:: Megan Wong & Simon JD Cox, _ANSIS Ontology_. Community proposed data standard (21 July 2022). https://raw.githack.com/ANZSoilData/def-au-domain/main/doc/domain.html[https://anzsoil.org/def/au/domain]

[[DCAT]] DCAT:: World Wide Web Consortium, _Data Catalog Vocabulary (DCAT) - Version 3_, W3C Recommendation (22 August 2024). https://www.w3.org/TR/vocab-dcat-3/

[[EIADP]] EIADP:: Department of Climate Change, Energy and the Environment, _EIA Data Profile_, Community proposed data standard (15 May 2025), https://linked.data.gov.au/def/eia-dp

[[ETS]] ETS:: Schneider, F.D., Jochum, M., Le Provost, G., Ostrowski, A., Penone, C. and Simons, N.K., _Ecological Trait-data Standard_ v0.10, Community data standard (28 March 2019) https://doi.org/10.5281/zenodo.2605377

[[GEO]] GeoSPARQL:: Open Geospatial Consortium, _OGC GeoSPARQL - A Geographic Query Language for RDF Data, Version 1.1_, OGC® Implementation Specification (2024). http://www.opengis.net/doc/IS/geosparql/1.1

[[LOCIDP]] LOCIDP:: Geoscience Australia, _Loc-I Data Profile_, Semantic Web profile (3 April 2021). https://linked.data.gov.au/def/loci-dp

[[NSLMODEL]] NSLMODEL: Centre for Australian National Biodiversity Research, _National Species List - Semantic Web Model_ (15 October 2023). https://linked.data.gov.au/def/nsl

[[OWL]] OWL:: World Wide Web Consortium, _OWL 2 Web Ontology Language Document Overview (Second Edition)_, W3C Recommendation (11 December 2012). https://www.w3.org/TR/owl2-overview/

[[PROF]] Profiles Vocabulary:: World Wide Web Consortium, _The Profiles Vocabulary_, W3C Working Group Note (18 December 2019). https://www.w3.org/TR/dx-prof/

[[RDF]] RDF:: World Wide Web Consortium, _RDF 1.1 Concepts and Abstract Syntax_, W3C Recommendation (25 February 2014). https://www.w3.org/TR/rdf11-concepts/

[[SDO]] schema.org:: W3C Schema.org Community Group, _schema.org_, Semantic Web model (2015). https://schema.org

[[SHACL]] SHACL:: World Wide Web Consortium, _Shapes Constraint Language (SHACL)_, W3C Recommendation (20 July 2017). https://www.w3.org/TR/shacl/

[[SKOS]] SKOS:: World Wide Web Consortium, _SKOS Simple Knowledge Organization System_, W3C Recommendation (18 August 2009). Semantic Web model. https://www.w3.org/TR/skos-reference/

[[VOCPUB]] VOCPUB:: Australian Government Linked Data Working Group, _VocPub Profile of SKOS_, Australian community standard (2020). https://linked.data.gov.au/def/vocpub